name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project and tools
        run: |
          python -m pip install --upgrade pip
          pip install .
          python -c "import duckdb; duckdb.install_extension('spatial')"
          pip install coverage

      - name: Run unittests with coverage
        env:
          PYTHONWARNINGS: ignore::ResourceWarning
          PYTHONPATH: src
        run: |
          coverage run -m unittest discover -s test -p "test_*.py"
          coverage report -m --omit="test/*"
          coverage xml
